# Generated by Django 2.0.13 on 2019-02-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Type')),
            ],
        ),
        migrations.AddField(
            model_name='development',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.RemoveField(
            model_name='development',
            name='status',
        ),
        migrations.AddField(
            model_name='development',
            name='status',
            field=models.ManyToManyField(blank=True, to='developments.Type'),
        ),
    ]
