# Generated by Django 2.0.13 on 2019-04-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0007_auto_20190409_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='description',
            field=models.TextField(max_length=256, verbose_name='Resumen'),
        ),
    ]
