# Generated by Django 2.0.13 on 2019-04-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0008_auto_20190411_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='about',
            field=models.TextField(max_length=2056, verbose_name='Acerca del desarrollo'),
        ),
        migrations.AlterField(
            model_name='development',
            name='description',
            field=models.TextField(max_length=2056, verbose_name='Resumen'),
        ),
    ]
