# Generated by Django 2.0.13 on 2019-04-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0009_auto_20190411_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='about',
            field=models.TextField(max_length=1056, verbose_name='Acerca del desarrollo'),
        ),
        migrations.AlterField(
            model_name='development',
            name='description',
            field=models.TextField(max_length=1056, verbose_name='Resumen'),
        ),
    ]
